### ISSUE TITLE
Wii U case branch detection

### ISSUE THREAD

**Issue by rajkosto** [aerosoul94/ida_game_elf_loaders#3]
You said you would eventually add this in, how is it progressing ? Having the switches as they are now is really ugly/inconvenient.

**Comment by aerosoul94** [comment]
Jump tables are handled by processor modules (the modules within the proc/ directory). Although possible, it would be ideal as a plugin rather than a loader (see [PPCJT](https://github.com/kakaroto/ps3ida/blob/master/plugins/PPCJT/src/ppcjt.cpp) as an example). The issue has been fixed (inaccurately I will add) in IDA 7.0 anyway.
